name: sine
description: A periodic episode tracker app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^3.9.0
  flutter_linkify: ^3.1.3
  flutter_redux: ^0.6.0
  json_serializable: ^3.3.0
  material_design_icons_flutter: 4.0.5245 # fixed version b/c not semver
  package_info: ^0.4.0
  path_provider: ^1.6.9
  redux_persist: ^0.8.4
  supercharged: ^1.5.1
  uuid: ^2.0.4
  url_launcher: ^5.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9
  lint: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png

flutter_native_splash:
  android: true
  ios: true
  image: assets/splash/splash.png
  color: "#2196f3"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
